### ISSUE TITLE
Requires > 1.4

### ISSUE THREAD

**Issue by hearnsj** [weymouth/WaterLily#3]
The code looks interesting! Just a commen treally - does it really require >1.5 version?
Current stable is 1.4.2 and I have that installed.

**Comment by weymouth** [comment]
See https://discourse.julialang.org/t/crazy-allocations-using-cartesianindices/42262. The code will run in 1.4, but it allocates memory which slows it down a lot. 1.5 pushes improvements to `CartesianIndices`, which I use throughout the code (to make it pretty!) Using 1.5, the solver only allocated memory into the time step and pressure solver history vectors - a few kb at most. Since this is a totally experimental package, it seemed silly not to use 1.5.
